name: ivorywalletsolution
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Auth Datafile this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

#################################################################################
#  D:\Flutter projects\ivorywalletsolution>flutter --version                    #
#  Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git      #
#  Framework • revision 18116933e7 (8 months ago) • 2021-10-15 10:46:35 -0700   #
#  Engine • revision d3ea636dc5                                                 #
#  Tools • Dart 2.14.4                                                          #
#################################################################################

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_widgets: ^1.1.0
  circular_menu: ^1.1.2
  syncfusion_flutter_charts: ^20.1.48
  flutter_slidable: 0.6.0
  intl: ^0.17.0
  rxdart: '>=0.18.1'
  flutter_secure_storage: ^4.1.0
  sqflite: ^2.0.0+3
  local_auth: 1.1.0
  data_tables: ^1.4.0
  file_picker: ^4.4.0
  share: ^2.0.4
  animations: ^2.0.0
  simple_cluster: ^0.3.0
  speech_to_text: ^5.6.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon/Icon.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # AppDrawerRelatedImages
    #icon
   - assets/AppIcon/Icon.png
   - assets/AppIcon/Icon.jpg

    #homepage
   - assets/HomepagePics/expenses.png
   - assets/HomepagePics/incomes.png
   - assets/HomepagePics/overview.png

    #categories

      #addNewCategory
   - assets/CategoryIcons/AddMore/addNewCategory.png

    #incomeandexpenses page pics
   - assets/IncomePagePics/all_accounts.png

      #incomes
   - assets/CategoryIcons/Incomes/bank.png
   - assets/CategoryIcons/Incomes/bitcoin.png
   - assets/CategoryIcons/Incomes/building.png
   - assets/CategoryIcons/Incomes/creditcard.png
   - assets/CategoryIcons/Incomes/saving.png
   - assets/CategoryIcons/Incomes/wallet.png

      #expenses
   - assets/CategoryIcons/Expenses/beer.png
   - assets/CategoryIcons/Expenses/beverages.png
   - assets/CategoryIcons/Expenses/calls.png
   - assets/CategoryIcons/Expenses/clothes.png
   - assets/CategoryIcons/Expenses/coffee.png
   - assets/CategoryIcons/Expenses/education.png
   - assets/CategoryIcons/Expenses/food.png
   - assets/CategoryIcons/Expenses/games.png
   - assets/CategoryIcons/Expenses/groceries.png
   - assets/CategoryIcons/Expenses/health.png
   - assets/CategoryIcons/Expenses/house.png
   - assets/CategoryIcons/Expenses/joy.png
   - assets/CategoryIcons/Expenses/music.png
   - assets/CategoryIcons/Expenses/pets.png
   - assets/CategoryIcons/Expenses/plane.png
   - assets/CategoryIcons/Expenses/security.png
   - assets/CategoryIcons/Expenses/shopping.png
   - assets/CategoryIcons/Expenses/smoking.png
   - assets/CategoryIcons/Expenses/snack.png
   - assets/CategoryIcons/Expenses/sports.png
   - assets/CategoryIcons/Expenses/subscribtions.png
   - assets/CategoryIcons/Expenses/vehicle.png

      #Transection Background
   - assets/TransectionsBackgroundImage/background.jpg

      #Budget setter icons
   - assets/Budget page/cash.png
   - assets/Budget page/creditcards.png

    #Budget setter backgrounds
   - assets/Budget page/Backgrounds/1.jpg
   - assets/Budget page/Backgrounds/2.jpg
   - assets/Budget page/Backgrounds/3.jpg
   - assets/Budget page/Backgrounds/4.jpg
   - assets/Budget page/Backgrounds/5.jpg

     #Overview page backgrounds
   - assets/OverviewPage/scatter-graph.png

    #Settings page
   - assets/SettingsPage/Settings.jpg

    #Introduction screen
   - assets/introduction_animation/

    #App Drawer(Account) screen and helper invite and so 0n
   - assets/AppDrawerRelatedImages/

    #Prediction Window
   - assets/fitness_app/
   - assets/PredictorScreen/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: ShinePersonalUse
      fonts:
        - asset: assets/fonts/ShinePersonalUse-KPDW.ttf

    - family: SelfDeceptionRegular
      fonts:
        - asset: assets/fonts/SelfDeceptionRegular-ALLWA.ttf

    - family: NolluqapersonaluseRegular
      fonts:
        - asset: assets/fonts/NolluqapersonaluseRegular-VGMge.otf

    - family: Boldblaster
      fonts:
        - asset: assets/fonts/BoldblasterItalic-K7pMp.otf

    - family: FelonastSC
      fonts:
        - asset: assets/fonts/FelonastSC-ExtraLight.ttf

    - family: amasis-mt-std-black
      fonts:
        - asset: assets/fonts/amasis-mt-std-black.otf

    - family: arlrdbd
      fonts:
        - asset: assets/fonts/arlrdbd.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf




  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

